server {
    listen 80;
    server_name 98.93.241.164;
    return 301 https://$host$request_uri;
}
 
server {
    listen 443 ssl;
    server_name 98.93.241.164;
 
    ssl_certificate     /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_dhparam         /etc/nginx/ssl/dhparam.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
 
    root  /var/www/mysite;
    index index.html;
 
    include /etc/nginx/snippets/security-headers.conf;
 
    error_page 404 /404.html;
    error_page 403 /403.html;
    location = /404.html { internal; }
    location = /403.html { internal; }
 
    location / {

    limit_req  zone=req_limit burst=20 nodelay;
    limit_conn conn_limit 10;

        add_header X-Host        $host;
        add_header X-Client-IP   $remote_addr;
        add_header X-Request-URI $request_uri;
        try_files $uri $uri/ =404;
    }
 
    location /api/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-URI   $request_uri;

    proxy_cache            my_cache;
    proxy_cache_valid      200 302 10m;
    proxy_cache_valid      404     1m;
    proxy_cache_lock       on;
    add_header X-Cache-Status $upstream_cache_status always;



    }
 
    location /lb/ {
        proxy_pass http://backend_rr/;
    }

    location /old-page {
    rewrite ^/old-page$ /new-page.html last;
   }
 
    location /blog {
    return 301 /articles.html;
   }
 
    location ~ ^/products/(.*)$ {
    return 301 /items/$1;
   }

 
    location /admin {
        auth_basic           "Restricted Area";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;
        try_files $uri $uri/ =404;
    }
}
