server {
    listen 80;
    server_name site1.example.local;
 
    root  /var/www/site1/html;
    index index.html;
 
    access_log /var/log/nginx/site1-access.log detailed;
    error_log  /var/log/nginx/site1-error.log warn;
 
    location / {
        try_files $uri $uri/ =404;
    }
}
