server {
    listen 80;
    server_name site2.example.local;
 
    root  /var/www/site2/html;
    index index.html;
 
    access_log /var/log/nginx/site2-access.log detailed;
    error_log  /var/log/nginx/site2-error.log warn;
 
    location / {
        try_files $uri $uri/ =404;
    }
}
